language: ruby

rvm:
  - 2.6.3

cache: bundler

stages:
  - rubocop
  - rspec

jobs:
  include:
    - stage: rubocop
      script: bundle exec rubocop

    - stage: rspec
      services:
        - mongodb
      script: bundle exec rspec spec -f d
